### ISSUE TITLE
Add support for modules/plugins

### ISSUE THREAD

**Issue by yuchi** [tonylukasavage/grunt-titanium#30]
Of course within the `ti_run` tasks.

Do you think this is it worth considering it? Currently I either pass the `tiapp.xml` as a file in `ti_run` or just run a prebuilt app.

**Comment by yuchi** [comment]
I probably found a good case where this is desiderable. In the [`.travis.yml`](https://github.com/smclab/ti-superagent/blob/master/.travis.yml) for `ti-superagent` I initially thought I could test multiple Titanium SDKs, but that would mean to change the property in the `tiapp.xml`.

It would be great to just use `ti_run` for this.

**Comment by yuchi** [comment]
:triangular_flag_on_post: ping

**Comment by tonylukasavage** [comment]
Show me a proposed syntax for how you would like to introduce this functionality.

**Comment by yuchi** [comment]
I think we don’t need to actually **install** the modules, just having them **set up** in the *tiapp.xml*.

Something along the lines of (`✔︎` marks my personal preference):

```js
grunt.initConfig({
  ti_run: {
    options: {
      create: {

        // Modules — option A
        modules: { 'superagent:commonjs': '1.0.0' },
        // Modules — option B (✔︎)
        modules: { commonjs: { superagent: '1.0.0' } },
        // Modules — option C (gitTio style) (✔︎)
        modules: [ 'superagent@1.0.0:commonjs' ],
        // Modules — option D
        modules: [ { id: 'superagent', platform: 'commonjs', version: 'latest' } ],

        // Plugins — option A (✔︎)
        plugins: [ 'ti.alloy@latest', 'ti.alloy' ],
        // Plugins — option B (✔︎)
        plugins: { 'ti.alloy': 'latest', 'ti.something': '1.0.0' },
        // Plugins — option C
        modules: [ { id: 'ti.something', version: 'latest' } ]

      },
      build: {
        platform: 'ios'
      }
    },
    myapp: {
      files: { 'tmp/myapp': ['test/fixtures/myapp/**/*'] }
    }
  }
});
```

**Comment by yuchi** [comment]
If you give me your preference over this I’ll try to contribute an implementation.

Currently we’d like `ti-superagent` to be cross tested on multiple ‘stable’ Titanium SDK versions, specifically `3.2.x`, `3.3.x` and `3.5.x` because these are the ones we usually find in the wild. And because it’s the source of the only platform dependent code fragment of [`liferay-connector`](https://github.com/smclab/liferay-connector) it is stopping us from lowering the `minsdk` for that too.

**Comment by yuchi** [comment]
So guys, now that things have settled, could you give me your preference over this?

I’ll get a PR ASAP after that.

**Comment by yuchi** [comment]
Closing for obsolescence
